name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: ""
          git-user: ${{ secrets.GITHUB_USERNAME }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
